import { Exercise } from './types'

// export const excers: Exercise[] = [
//   {
//     id: 1,
//     title: 'Prve cvicenie',
//     text: 'text cvicenia',
//     versionLeft: 17,
//     leftCode: 'left code',
//     test: '',
//     versionRight: 20,
//     rightCode: 'right code',
//     editLeft: false,
//   },
//   {
//     id: 2,
//     title: 'Druhe cvicenie',
//     text: 'text cvicenia',
//     versionLeft: 17,
//     leftCode: 'left code',
//     test: 'left tests',
//     versionRight: 20,
//     rightCode: 'right code',
//     editLeft: true,
//   },
//   {
//     id: 3,
//     title: 'Tretie cvicenie',
//     text: 'text cvicenia',
//     versionLeft: 17,
//     leftCode: 'left code',
//     test: 'left tests',
//     versionRight: 20,
//     rightCode: 'right code',
//     editLeft: true,
//   },
//   {
//     id: 4,
//     title: 'Stvrte cvicenie',
//     text: 'text cvicenia',
//     versionLeft: 17,
//     leftCode: 'left code',
//     test: 'left tests',
//     versionRight: 20,
//     rightCode: 'right code',
//     editLeft: true,
//   },
// ]
